#!/bin/sh

### BEGIN INIT INFO
# Provides:             audioplayer
# Required-Start:       $local_fs $network $remote_fs $all 
# Required-Stop:        
# Default-Start:        3 5
# Default-Stop:         0 1 6
# Short-Description:    audioplayer
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Log in syslog
log()
{
	logger -t AudioPlayer $1
}

# Star IHM
StartIHM()
{
#	TEST=`ps -a | grep Read`
#	while [ -z "$TEST" ]
#	do   
#	sleep 1
	ReadIHM.sh &
#	log "state:$TEST"
#	done
}

case $1 in
  start)
	AudioEN.sh
	log "Power USB Device"
        InitDac.sh
	StartIHM
	log "Start IHM input"
	sleep 1;
	ProcessIO.sh &
	log "Start Process managing"	
 
  ;;


  stop)
	KillAllAudio.sh
	log "Kill Audio"
	PCM1792AReset
	SRC4392Reset
	log "Reset PCM1792A and SRC4392"

  ;;
  restart|force-reload)
        $0 stop
	sleep 1
	$0 start
  ;;

  *)
	N=/etc/init.d/AudioPlayer
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0 
