#!/bin/sh

### BEGIN INIT INFO
# Provides:             gpioinit 
# Required-Start:       $local_fs $network $remote_fs $all 
# Required-Stop:        
# Default-Start:        3 5
# Default-Stop:         0 1 6
# Short-Description:    gpioinit
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Log in syslog
log()
{
	logger -t AudioPlayer $1
}

case $1 in
  start)
        mkdir /gpio
        if [ ! -d "/sys/class/gpio/gpio60" ]; then 
            echo 60 > /sys/class/gpio/export 
        fi
        if [ ! -d "/sys/class/gpio/gpio48" ]; then 
            echo 48 > /sys/class/gpio/export 
        fi
	ln -s /sys/class/gpio/gpio60 /gpio/UsbPW
	ln -s /sys/class/gpio/gpio48 /gpio/AudioOutPW
	log "Create gpio link"	
        echo out > /gpio/UsbPW/direction
        echo out > /gpio/AudioOutPW/direction
        echo 1 > /gpio/UsbPW/value
        echo 1 > /gpio/AudioOutPW/value
	log "config gpio out,high"	
 
  ;;

  stop)
        echo in > /gpio/AudioUsbPW/direction
        echo 0 > /gpio/AudioUsbPW/value
	log "config gpio in,low"	
  	rm -r /gpio
	log "remove gpio link"	

  ;;

  restart|force-reload)
        $0 stop
	sleep 1
	$0 start
  ;;

  *)
	N=/etc/init.d/gpioinit
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0 
